services:
  backend:
    build: ./backend
    container_name: aerosig-backend
    ports:
      - "8000:8000"
    networks:
      - aerosig-network

  frontend:
    build: ./frontend
    container_name: aerosig-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - aerosig-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: aerosig-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - aerosig-network

networks:
  aerosig-network:
    driver: bridge

volumes:
  jenkins_home:
